### ISSUE TITLE
Is it possible to inject signals in class ?

### ISSUE THREAD

**Issue by flashultra** [peteshand/signals#1]
I'm using many callbacks ( via signals) and if I want to use singleton ( for dispatch and add in different class ) for each signal I should call at example SignalSingletonClass.get(mysignal1).add / dispatch. 
Is it possible to use some kind of inject ?
 At example I'm using minject at the moment setting all signals ```asSingleton``` and calling ```injectInto(target)```
 Which bring declaration of signal to something like ```@inject public var mySignal1:MySginal1; ....```  and one call of injectInto

**Comment by peteshand** [comment]
Hi there.

Unfortunately I'm not familiar with minject, so I'm exactly how it would work with that. I typically robotlegs which I imagine works fairly similar and indeed use injection all over the place. Take a look at https://github.com/openfl/robotlegs. that being said the documentation is a few years old and we have added quite a new features, biggest probably being upgrading from rtti (runtime) reflection to macro reflection.

**Comment by flashultra** [comment]
Hi,
I was looking for simple / fast way to inject signal info to simulate some kind of MVVM pattern , but yes minject is good enough for what i using it . 
 About robotlegs, I was checking it some years ago ( on AS3 target ) , but I go in other direction. 
Thank you for your feedback.
