### ISSUE TITLE
Signal2.hx:5: characters 41-42 : Unexpected ,

### ISSUE THREAD

**Issue by alamboley** [peteshand/signals#4]
Hey, thanks for this nice lib!

While trying to use the Signal2 class, I get a compiler error from Haxe 3.4.7:  
Signal2.hx:5: characters 41-42 : Unexpected ,

Could you give it a try?

**Comment by peteshand** [comment]
Yeah this Lib is using Haxe 4 syntax.
Is there a reason you're still on v3.x?

**Comment by alamboley** [comment]
Well, I'm using https://github.com/pixijs/pixi-haxe which isn't Haxe4 ready for the moment.

**Comment by peteshand** [comment]
There is a 4.x version available:
https://github.com/notboring/pixi-haxe
